CREATE TABLE IF NOT EXISTS Friendship (
    FromUserId INT NOT NULL REFERENCES Client (Id) ON DELETE CASCADE,
    ToUserId INT NOT NULL REFERENCES Client (Id) ON DELETE CASCADE,
    Accepted BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (FromUserId, ToUserId)
);