CREATE TABLE IF NOT EXISTS ChatToClient (
    Id SERIAL PRIMARY KEY,
    UserId INT NOT NULL REFERENCES Client (Id) ON DELETE CASCADE,
    ChatId INT NOT NULL REFERENCES Chat(Id) ON DELETE CASCADE ,
    Key BIT(256) NOT NULL,
    IsAdmin BOOLEAN NOT NULL DEFAULT FALSE,
    JoinedAt TIMESTAMP NOT NULL DEFAULT now(),
    LeftAt TIMESTAMP DEFAULT NULL
);