CREATE TABLE IF NOT EXISTS Chat (
    Id SERIAL PRIMARY KEY,
    OwnerId INT REFERENCES Client (Id) ON DELETE SET NULL,
    Name VARCHAR(150) NOT NULL,
    Description VARCHAR(255),
    CreatedAt TIMESTAMP NOT NULL DEFAULT now()
);
