CREATE TABLE IF NOT EXISTS Message (
    Id SERIAL PRIMARY KEY,
    FromUserId INT NOT NULL REFERENCES Client (Id) ON DELETE CASCADE,
    ChatId INT NOT NULL REFERENCES Chat(Id) ON DELETE CASCADE,
    Message VARCHAR(1000) NOT NULL,
    Timestamp TIMESTAMP NOT NULL DEFAULT now()
);