version: '3.9'

volumes:
  data:

services:
  db:
    build: ./database
    container_name: messenger-db
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  app:
    depends_on:
      - db
    build: .
    container_name: messenger-app
    ports:
      - "8080:8080"
    environment:
      - DB_SERVER=db
    links:
      - db



