version: '3.9'

services:
  webserver:
    container_name: webapp-server
    build: ./app
    restart: on-failure
    depends_on:
      - backend
    ports:
      - "80:80"

  backend:
    container_name: spring-server
    build: backend
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend
    networks:
      - spring-cloud-network

  db:
    image: postgres:15.2-alpine3.17
    restart: on-failure
    env_file:
      - ./database/config.env
    ports:
      - '5432:5432'

networks:
  spring-cloud-network:
    driver: bridge