version: '3.9'

services:
  webserver:
    build: ./app
    restart: on-failure
    depends_on:
      - backend
    ports:
      - "80:80"

  backend:
    build: ./backend
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: messenger
      POSTGRES_PASSWORD: WrP3w336gbR2DIUztKjSF4istgp4b2qHW7E43det
      POSTGRES_DB: messenger
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./database/migration:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
