version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: messenger
      POSTGRES_PASSWORD: WrP3w336gbR2DIUztKjSF4istgp4b2qHW7E43det
      POSTGRES_DB: messenger
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./migration:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
